server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
  ####Spring Cloud Consul for Service Discovery
  cloud:
    consul:
      host: 43.137.8.130
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true #优先使用服务ip进行注册
        heartbeat:
          enabled: true
        #hostname: 127.0.0.1  # 可选配置项，指定服务注册时使用的 IP 地址，不配置时默认使用本机 IP 地址