server:
  port: 80

spring:
  application:
    name: cloud-consumer-openfeign-order
  cloud:
    consul:
      host: 43.137.8.130
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true